### ISSUE TITLE
Improve XML-RPC endpoint discovery (including redirects handling)

### ISSUE THREAD

**Issue by aforcier** [wordpress-mobile/WordPress-Stores-Android#26]
Currently, `HTTP`>`HTTPS` (presumably also `HTTP`>`HTTP`) redirects are followed, but there's an issue when `POST`ing to `XML-RPC`: the `POST` isn't re-submitted, and a `GET` request is made instead, which results in a `405` error.

This is following HTTP guidelines, which try to limit cases of submitting multiple `POST`s, or submitting `POST`s to other URLs, without the user's explicit consent.

On WPAndroid we probe for the `rsd` file with `GET` first. We should do the same for Stores, as we improve XML-RPC endpoint discovery in general (see #4).

**Comment by maxme** [comment]
We should reuse the [discovery code from wpandroid ](https://github.com/wordpress-mobile/WordPress-Android/blob/b34e383dfdbdb420afc848005778bf6313abc351/WordPress/src/main/java/org/xmlrpc/android/XMLRPCUtils.java#L316)

**Comment by maxme** [comment]
Make sure to add a "real life" redirect test to `tests.properties` for instance http://bia.is/wpbeta redirects https://bia.is/wpbeta

**Comment by aforcier** [comment]
Fixed in #33.
